### ISSUE TITLE
Errores no controlados

### ISSUE THREAD

**Issue by xavibignell** [eusonlito/redsys-Messages#6]
Buenas,
Tengo un error de bizum y no está controlado, podrias añadir este código de error? 

![image](https://user-images.githubusercontent.com/62743766/77739949-b2d13a00-7012-11ea-847f-69f1f20ed725.png)

Si quieres revisar los códigos nuevos te adjunto una articulo

https://www.kebes.es/2019/09/16/codigos-respuesta-tpv-redsys/

Gracias

**Comment by eusonlito** [comment]
Okey, lo haré lo antes posible.

La referencia original es https://pagosonline.redsys.es/codigosRespuesta.html

**Comment by xavibignell** [comment]
Perfecto,

Muchas gracias

**Comment by xavibignell** [comment]
He intentado crear una rama para que me hagas el merge a master pero no tengo permisos, te paso el código que hay que añadir en Response-common.php

`'9485' => array(
        'code' => '9485',
        'message' => 'DENEGACIÓN EN LA DEVOLUCIÓN',
        'detail' => 'Error producido por la denegación de la devolución.'
    ),`

Gracias,

**Comment by eusonlito** [comment]
Hoy espero poder dejarlo listo

**Comment by xavibignell** [comment]
Perfecto, muchas gracias! :)

**Comment by eusonlito** [comment]
He registrado todos los errors disponibles en Redsys y he actualizado el formato.

Debería funcionar exactamente igual que antes, pero si puedes haz la prueba cambiando el repositorio a `master` y así saco una nueva release con esta versión.

Gracias!

**Comment by xavibignell** [comment]
Buenas,
Estoy probando y me está fallando al actualizar el composer porque el redsys/tpv requiere una versión de redsys/messages que no sea dev.

![image](https://user-images.githubusercontent.com/62743766/78660763-f1e27380-78cd-11ea-8de9-72e9201061f6.png)

**Comment by eusonlito** [comment]
En tu composer json, prueba a forzar la compatibilidad añadiendo:

```json
"require": {
    "redsys/messages": "master@dev"
}
```

**Comment by xavibignell** [comment]
Sigo teniendo este problema
![image](https://user-images.githubusercontent.com/62743766/78662425-a67d9480-78d0-11ea-8455-b0cbaeac252a.png)

**Comment by eusonlito** [comment]
Vale, he sacado una nueva release de este paquete, así que ahora ya debería actualizarse directamente.

**Comment by xavibignell** [comment]
Lo acabo de probar y funciona perfecto!

Muchísimas gracias,

Un saludo!
