### ISSUE TITLE
New messages in Redsys

### ISSUE THREAD

**Issue by frandss** [eusonlito/redsys-Messages#7]
Hola Eusonlito, ¿sigues manteniendo este proyecto? Hay nuevos mensajes de error en Redsys que no están aquí registrados, por ejemplo el 9673 - SIS0673 - Bizum. Operación cancelada. El usuario no desea seguir.

¿Sería posible que lo actualizaras?¿Prefieres que te haga un pull request?

**Comment by eusonlito** [comment]
Vale, revisaré la documentación oficial para buscar los nuevos códigos: https://pagosonline.redsys.es/codigosRespuesta.html

Gracias!

**Comment by eusonlito** [comment]
Listo!
